version: 1.0.1.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
before_build:
  - nuget restore
build:
  verbosity: minimal
  publish_nuget: true
artifacts:
  - path: Xnapshot\bin\Release\Xnapshot.dll
    name: Xnapshot.dll