version: 2.0.{build}

pull_requests:
  do_not_increment_build_number: true

configuration: Release

before_build:
  - nuget restore Xnapshot\packages.config -SolutionDirectory .
  
build:
  verbosity: minimal
  
after_build:
  - ps: nuget pack Xnapshot.nuspec -Version $env:APPVEYOR_BUILD_VERSION
  
artifacts:
  - path: Xnapshot\bin\Release\Xnapshot.dll
    name: Xnapshot.dll
  - path: Xnapshot.*.nupkg
    name: Xnapshot.$env:APPVEYOR_BUILD_VERSION.nupkg
  
deploy:
  provider: NuGet
  api_key: 
    secure: 0Qdb2JFO+bwNGuu31r12mbWEGHnFI3DHGx9ta5wxRoAEVwS7jrXjqtN5KD3tAAwx
  skip_symbols: true
  artifact: Xnapshot.$env:APPVEYOR_BUILD_VERSION.nupkg