version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

configuration: Release
platform: Any CPU

before_build:
  - nuget restore
  
build:
  verbosity: minimal
  
after_build:
  - ps: nuget pack Xnapshot.nuspec -Version $env:APPVEYOR_BUILD_VERSION
  
artifacts:
  - path: Xnapshot\bin\Release\Xnapshot.dll
    name: Xnapshot.dll
  - path: Xnapshot.*.nupkg